In [3]:
import os
os.getcwd()

'/Users/saifalikhanmangan/customer-support-data-platform/notebooks'

In [4]:
import sys
from pathlib import Path

sys.path.append(str(Path("..").resolve()))

In [5]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
DATA_PATH = BASE_DIR / "data" / "raw" / "issues.csv"

issues = pd.read_csv(DATA_PATH)
issues.head()

,id,started,ended,issue_num,issue_proj,issue_reporter,issue_assignee,issue_contr_count,issue_type,issue_priority,...,wf_cancelled,wfe_cancelled,wf_under_review,wfe_under_review,wf_approved,wfe_approved,wf_pending_deployment,wfe_pending_deployment,wf_total_time,processing_steps
0,11887.0,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00,186.0,d1z0,4olg,NaN,1.0,Ticket,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,1992.0,2
1,11890.0,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00,190.0,d1z0,4olg,NaN,1.0,Ticket,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,95044.0,2
2,11904.0,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00,198.0,d1z0,4ohk,4ohk,1.0,Ticket,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,435207.0,2
3,11907.0,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00,209.0,d1z0,4olg,NaN,1.0,Vacation,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,54.0,2
4,11912.0,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00,217.0,d1z0,4ohk,4ohk,1.0,Story,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,491755.0,2

In [6]:
issues.columns
issues.info()

<class 'pandas.DataFrame'>
RangeIndex: 66691 entries, 0 to 66690
Data columns (total 58 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             66691 non-null  float64
 1   started                        66691 non-null  str
 2   ended                          66691 non-null  str
 3   issue_num                      66691 non-null  float64
 4   issue_proj                     66691 non-null  str
 5   issue_reporter                 66691 non-null  str
 6   issue_assignee                 35644 non-null  str
 7   issue_contr_count              66691 non-null  float64
 8   issue_type                     66691 non-null  str
 9   issue_priority                 66691 non-null  str
 10  issue_created                  66691 non-null  str
 11  issue_resolution_date          65838 non-null  str
 12  issue_resolution               65838 non-null  str
 13  issue_status                   66691 non-null  str
 14  issue_comments_count           66691 non-null  int64
 15  last_change_date               66690 non-null  str
 16  wf_in_review                   77 non-null     float64
 17  wfe_in_review                  66691 non-null  int64
 18  wf_deployment                  135 non-null    float64
 19  wfe_deployment                 66691 non-null  int64
 20  wf_resolved                    28145 non-null  float64
 21  wfe_resolved                   66691 non-null  int64
 22  wf_open                        66613 non-null  float64
 23  wfe_open                       66691 non-null  int64
 24  wf_monitoring                  518 non-null    float64
 25  wfe_monitoring                 66691 non-null  int64
 26  wf_done                        860 non-null    float64
 27  wfe_done                       66691 non-null  int64
 28  wf_pending_customer_approval   254 non-null    float64
 29  wfe_pending_customer_approval  66691 non-null  int64
 30  wf_rejected                    112 non-null    float64
 31  wfe_rejected                   66691 non-null  int64
 32  wf_testing_monitoring          290 non-null    float64
 33  wfe_testing_monitoring         66691 non-null  int64
 34  wf_in_progress                 36747 non-null  float64
 35  wfe_in_progress                66691 non-null  int64
 36  wf_reopened                    2123 non-null   float64
 37  wfe_reopened                   66691 non-null  int64
 38  wf_to_do                       785 non-null    float64
 39  wfe_to_do                      66691 non-null  int64
 40  wf_validation                  2961 non-null   float64
 41  wfe_validation                 66691 non-null  int64
 42  wf_resolved_under_monitoring   1931 non-null   float64
 43  wfe_resolved_under_monitoring  66691 non-null  int64
 44  wf_closed                      1595 non-null   float64
 45  wfe_closed                     66691 non-null  int64
 46  wf_waiting                     19704 non-null  float64
 47  wfe_waiting                    66691 non-null  int64
 48  wf_cancelled                   160 non-null    float64
 49  wfe_cancelled                  66691 non-null  int64
 50  wf_under_review                1821 non-null   float64
 51  wfe_under_review               66691 non-null  int64
 52  wf_approved                    1630 non-null   float64
 53  wfe_approved                   66691 non-null  int64
 54  wf_pending_deployment          1413 non-null   float64
 55  wfe_pending_deployment         66691 non-null  int64
 56  wf_total_time                  66691 non-null  float64
 57  processing_steps               66691 non-null  int64
dtypes: float64(24), int64(22), str(12)
memory usage: 29.5 MB

In [7]:
issues["issue_priority"].value_counts()

issue_priority
unknown    33965
Medium     24788
High        4554
Highest     2084
Blocker      656
Low          560
Lowest        84
Name: count, dtype: int64

In [8]:
issues["issue_priority"].isna().sum()

np.int64(0)

In [9]:
core_cols = [
    "id",
    "issue_priority",
    "issue_type",
    "issue_proj",
    "issue_contr_count",
    "issue_created",
    "issue_resolution_date"
]

issues_core = issues[core_cols]
issues_core.head()

,id,issue_priority,issue_type,issue_proj,issue_contr_count,issue_created,issue_resolution_date
0,11887.0,Medium,Ticket,d1z0,1.0,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00
1,11890.0,Medium,Ticket,d1z0,1.0,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00
2,11904.0,Medium,Ticket,d1z0,1.0,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00
3,11907.0,Medium,Vacation,d1z0,1.0,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00
4,11912.0,Medium,Story,d1z0,1.0,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00

In [10]:
issues_core.info()

<class 'pandas.DataFrame'>
RangeIndex: 66691 entries, 0 to 66690
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     66691 non-null  float64
 1   issue_priority         66691 non-null  str
 2   issue_type             66691 non-null  str
 3   issue_proj             66691 non-null  str
 4   issue_contr_count      66691 non-null  float64
 5   issue_created          66691 non-null  str
 6   issue_resolution_date  65838 non-null  str
dtypes: float64(2), str(5)
memory usage: 3.6 MB

In [11]:
issues_core["issue_priority"] = issues_core["issue_priority"].replace(
    {"unknown": "Medium"}
)
issues_core["issue_priority"].value_counts()

issue_priority
Medium     58753
High        4554
Highest     2084
Blocker      656
Low          560
Lowest        84
Name: count, dtype: int64

In [12]:
urgent_labels = {"High", "Highest", "Blocker"}

issues_core["priority_bin"] = issues_core["issue_priority"].apply(
    lambda x: 1 if x in urgent_labels else 0
)

issues_core["priority_bin"].value_counts()

priority_bin
0    59397
1     7294
Name: count, dtype: int64

In [13]:
issues_core.head()

,id,issue_priority,issue_type,issue_proj,issue_contr_count,issue_created,issue_resolution_date,priority_bin
0,11887.0,Medium,Ticket,d1z0,1.0,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00,0
1,11890.0,Medium,Ticket,d1z0,1.0,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00,0
2,11904.0,Medium,Ticket,d1z0,1.0,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00,0
3,11907.0,Medium,Vacation,d1z0,1.0,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00,0
4,11912.0,Medium,Story,d1z0,1.0,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00,0

In [14]:
issues_core["issue_created"] = pd.to_datetime(
    issues_core["issue_created"],
    format="mixed",
    utc=True
)

issues_core["issue_resolution_date"] = pd.to_datetime(
    issues_core["issue_resolution_date"],
    format="mixed",
    utc=True,
    errors="coerce"
)

In [15]:
issues_core["resolution_hours"] = (
    issues_core["issue_resolution_date"] - issues_core["issue_created"]
).dt.total_seconds() / 3600

issues_core["created_hour"] = issues_core["issue_created"].dt.hour
issues_core["created_dayofweek"] = issues_core["issue_created"].dt.dayofweek

In [16]:
issues_core[["resolution_hours"]].describe()

       resolution_hours
count      65838.000000
mean       18482.548659
std        27805.944918
min            0.000833
25%          124.322778
50%          837.807849
75%        36508.149060
max        99220.536076

In [17]:
DATA_sample_utterances = BASE_DIR / "data" / "raw" / "sample_utterances.csv"
issues_sample_utterances = pd.read_csv(DATA_sample_utterances)

issues_sample_utterances.head()

,issueid,id,comment_seq,utr_seq,author,created,is_private,actionbody,author_role
0,1004298.0,211718014.0,0,0,.wy0w13yhr,2022-01-02 11:12:51+00:00,0.0,dear ph_name team,reporter
1,1004298.0,211718014.0,0,1,.wy0w13yhr,2022-01-02 11:12:51+00:00,0.0,we need your urgent support to fix list of vul...,reporter
2,1004298.0,211718014.0,0,2,.wy0w13yhr,2022-01-02 11:12:51+00:00,0.0,please provide resolution date before end of ‘...,reporter
3,1004298.0,1045407.0,1,0,z2w_x,2022-01-02 11:13:02+00:00,1.0,.,others
4,1004298.0,1045407.0,1,1,z2w_x,2022-01-02 11:13:02+00:00,1.0,problem: .,others

In [18]:
text_per_issue = (
    issues_sample_utterances
    .fillna({"actionbody": ""})
    .groupby("issueid")["actionbody"]
    .apply(lambda x: " ".join(x.astype(str)))
    .reset_index()
)

text_per_issue.head()

     issueid                                         actionbody
0  1004298.0  dear ph_name team we need your urgent support ...
1  1004357.0  greetings this ticket is created on the behalf...
2  1004361.0  greetings we are encountering a force logout i...
3  1004362.0  greetings in the ph_item  ph_user  when the us...
4  1004364.0  greetings please find the attached files as re...

In [19]:
issues_full = issues_core.merge(
    text_per_issue,
    left_on="id",
    right_on="issueid",
    how="left"
)

issues_full[["id", "issue_priority", "priority_bin", "actionbody"]].head()

        id issue_priority  priority_bin actionbody
0  11887.0         Medium             0        NaN
1  11890.0         Medium             0        NaN
2  11904.0         Medium             0        NaN
3  11907.0         Medium             0        NaN
4  11912.0         Medium             0        NaN

In [20]:
utterances = issues_sample_utterances.copy()

utterances = utterances[
    (utterances["author_role"] == "reporter") &
    (utterances["is_private"] == 0)
]

utterances = utterances[["issueid", "actionbody"]]
utterances.head()

      issueid                                         actionbody
0   1004298.0                                  dear ph_name team
1   1004298.0  we need your urgent support to fix list of vul...
2   1004298.0  please provide resolution date before end of ‘...
17  1004298.0                                     dear  ph_user
18  1004298.0  as requested we have listed application relate...

In [21]:
issue_text = (
    utterances
    .groupby("issueid")["actionbody"]
    .apply(lambda x: " ".join(x.dropna().astype(str)))
    .reset_index()
)

issue_text.head()

     issueid                                         actionbody
0  1004298.0  dear ph_name team we need your urgent support ...
1  1004357.0  greetings this ticket is created on the behalf...
2  1004361.0  greetings we are encountering a force logout i...
3  1004362.0  greetings in the ph_item  ph_user  when the us...
4  1004364.0  greetings please find the attached files as re...

In [22]:
issues_full = issues_core.merge(
    issue_text,
    left_on="id",
    right_on="issueid",
    how="left"
)

issues_full["actionbody"] = issues_full["actionbody"].fillna("")
issues_full[["actionbody", "priority_bin"]].head()

  actionbody  priority_bin
0                        0
1                        0
2                        0
3                        0
4                        0

In [23]:
issues_full["actionbody"].str.len().describe()

count    66691.000000
mean         3.222384
std         80.250658
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      10992.000000
Name: actionbody, dtype: float64

In [24]:
(issues_full["actionbody"].str.len() > 0).mean()

np.float64(0.005338051611161926)

In [25]:
issues_full.loc[
    issues_full["actionbody"].str.len() > 0,
    ["actionbody", "priority_bin"]
].head()

                                              actionbody  priority_bin
44875  dears, kindly note that all the transactions i...             1
48010  kindly, no edit option appeared for following ...             1
49188  dears, if we set an account to switch default ...             1
50624  ph_name reply ph_technical file rejected by ph...             1
51314  dears, kindly note that a system error appear ...             0

In [26]:
feature_cols = [
    "issue_contr_count",
    "created_hour",
    "created_dayofweek",
    "resolution_hours"
]

X = issues_full[feature_cols].fillna(0)
y = issues_full["priority_bin"]

X.shape, y.shape

((66691, 4), (66691,))

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [29]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94     17820
           1       0.36      0.10      0.16      2188

    accuracy                           0.88     20008
   macro avg       0.63      0.54      0.55     20008
weighted avg       0.84      0.88      0.85     20008